[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio-tungstenite = "0.27.0"
tokio = { version = "1.46.1", features = ["rt-multi-thread", "rt", "macros", "io-std"] }
env_logger = "0.11.8"
log = "0.4.27"
futures-util = "0.3.31"
futures-channel = "0.3.31"
