name: Rust
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Frontend
      run: cargo build --verbose
      working-directory: frontend
    - name: Run Frontend Tests
      run: cargo test --verbose
      working-directory: frontend

  build_backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Backend
      run: cargo build --verbose
      working-directory: backend
    - name: Run Backend Tests
      run: cargo test --verbose
      working-directory: backend
